spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    username: assertuser
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false

    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
